### ISSUE TITLE
SEO Tag Gem

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#3]
https://github.com/jekyll/jekyll-seo-tag

Let's get this going towards the end...

jekyll-seo-tag adds the following metadata tags to your site:

Page title, with site title or description appended
Page description
Canonical URL
Next and previous URLs on paginated pages
JSON-LD Site and post metadata for richer indexing
Open Graph title, description, site title, and URL (for Facebook, LinkedIn, etc.)
Twitter Summary Card metadata

To enable the jekyll-seo-tag plugin add the following to your site’s  Gemfile:

```
gem 'jekyll-seo-tag'
And then add this to your site’s _config.yml file:
```

```
plugins:
   - jekyll-seo-tag
```
And finally add this right before `</head>` in your site’s template:

`{% seo %}`

Using the jekyll-seo-tag plugin#
The jekyll-seo-tag plugin will include any of the following list if included in your site’s `_config.yml`.

title - your website’s title (e.g., Racoon’s Website, Fox’s Blog). Google will only display the first 50-60 characters of a title, so be precise.
description - a short description of your website (e.g., A website featuring gifts for owl lovers). This appears below the title in a search result. You need to entice someone to click on your link in less than 320 characters.
url - the full URL of your site
author - global author information
logo - URL to a site-wide logo (e.g., /assets/fox-selfie.png)
You can add your site’s Twitter handle by inputting:

```
twitter: 
  username: rogertheracoon
```
For Facebook you can use the following properties:

facebook:app_id - a Facebook app ID for Facebook insights
facebook:publisher - a Facebook page URL or ID of the publishing entity
facebook:admins - a Facebook user ID for domain insights linked to a personal account
You can add one or more of these properties by inputting:

```
facebook:
  app_id: 987654321
  publisher: 987654321   
  admins: 987654321
```
You can specify social profiles using social:

name - If the user or organization name differs from the site’s name
links - An array of links to social media profiles.
You can add one or more of these properties by inputting:

```
social:
  name: Roger the Racoon
  links:
    - https://twitter.com/rogertheracoon
    - https://www.instagram/rogerracoon
    - https://www.facebook.com/roger.racoon
```
Use google_site_verification for verifying ownership via Google webmaster tools, or you can verify ownership with several services at once by inputting:

  ```
webmaster_verifications:
    google: 987654321
    bing: 987654321
    alexa: 987654321
```
